version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: contract_vue
    ports:
      - "80:80"  # 内部端口为80，与nginx配置中监听的80对应
    restart: always # always表容器运行发生错误时一直重启
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/home/
    expose:
      - "80"
